spring:
  config:
    import: env.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  name: Hospital Records
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 7776000000 #900000
      refresh-token:
        expiration: 7776000000


